name: software_brava
description: "Aplicativo móvel e painel administrativo SAMU Joinville"
publish_to: 'none' # Previne publicação acidental no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Requisições HTTP e conexão à API FastAPI
  http: ^1.2.0
  dio: ^5.4.0

  # Persistência Offline-First e Banco Local (SQLite)
  sqflite: ^2.3.0
  path: ^1.9.0

  # Detecção de rede
  connectivity_plus: ^5.0.2

  # Geolocalização GPS
  geolocator: ^10.1.0

  # Impressão térmica e PDF
  pdf: ^3.10.7
  printing: ^5.11.0

  # Dashboard e Gráficos
  fl_chart: ^0.66.0

  # Guarda segura de token JWT (LGPD)
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true